[project]
name = 'claritylance'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.claritylance]
path = 'contracts/claritylance.clar'
clarity_version = 4
epoch = 3.3

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
